name: learn_english
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  flutter_dotenv: ^6.0.0

# UI & animation
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  file_picker: ^10.3.3



# Firebase & Auth
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3

# State management
  get: ^4.7.2
  riverpod: ^3.0.3
  provider: ^6.1.5+1
  get_it: ^8.2.0

# Routing
  go_router: ^16.2.5

# Audio / Speech / TTS
  audioplayers: ^6.5.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1

# AI
  http: ^1.5.0
  google_generative_ai: ^0.4.7

# File & storage
  path_provider: ^2.1.5
  dio: ^5.9.0
  syncfusion_flutter_pdfviewer: ^31.2.2
  flutter_pdf_text: ^0.9.0
  read_pdf_text: ^0.3.1
  uuid: ^4.5.1

# Local DB

  hive: ^2.2.3
  hive_flutter: ^1.1.0

# Charts & Visualization
  fl_chart: ^0.70.0

# Shared preferences
  shared_preferences: ^2.5.3

  percent_indicator: ^4.2.5

# Localization
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets:
    - lib/resources/assets/icons/
    - lib/resources/assets/images/
    - lib/resources/assets/audios/
    - lib/resources/assets/lottie/
    - .env

  uses-material-design: true


