name: Deploy Flutter Web to Netlify

on:
  push:
    branches: [ main ]  # branch bạn muốn deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure build/web exists
        run: mkdir -p build/web


      - name: Copy _redirects for SPA
        run: cp web/_redirects build/web/_redirects

      - name: Build Web
        run: flutter build web --release



      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./build/web"
          production-branch: main
          deploy-message: "Auto deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

